//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerAPPv3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trailers_dbEntities3 : DbContext
    {
        public trailers_dbEntities3()
            : base("name=trailers_dbEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<trailer> trailer { get; set; }
        public virtual DbSet<user_system> user_system { get; set; }
        public virtual DbSet<movement_trailer> movement_trailer { get; set; }
        public virtual DbSet<tracking> tracking { get; set; }
    }
}
