//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerAPPv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class movement_trailer
    {
        public System.Guid id { get; set; }
        [Display(Name = "Trailer")]
        public Nullable<System.Guid> trailer_id { get; set; }
        [Display(Name = "Latitud")]
        public Nullable<decimal> latitude { get; set; }
        [Display(Name = "Longitud")]
        public Nullable<decimal> longitude { get; set; }
        [Display(Name = "Fecha y hora del movimiento")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> datetime { get; set; }
        [Display(Name = "Trailer")]
        public virtual trailer trailer { get; set; }
    }
}
