//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerAPPv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Newtonsoft.Json;

    public partial class tracking
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> trailer_id { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        [DataType(DataType.DateTime)]

        public Nullable<System.DateTime> datetime { get; set; }

        [JsonIgnore]
        public virtual trailer trailer { get; set; }
    }
}
