//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrailerAPPv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trailer()
        {
            this.movement_trailer = new HashSet<movement_trailer>();
            this.tracking = new HashSet<tracking>();
        }
    
        public System.Guid id { get; set; }
        [Display(Name = "Placa")]
        public string plate { get; set; }
        [Display(Name = "Modelo")]
        public string modelo { get; set; }
        [Display(Name = "Tipo de trailer")]
        public string tipo { get; set; }
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha de adquision")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> adquisition_datetime { get; set; }
        [Display(Name = "Estado del trailer")]
        public string status { get; set; }
        [Display(Name = "Linea")]
        public string linea { get; set; }
        [Display(Name = "Color")]
        public string color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movement_trailer> movement_trailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tracking> tracking { get; set; }
    }
}
